### ISSUE TITLE
Package Not Found!!

### ISSUE THREAD

**Issue by yashksaini-coder** [deepanshu414/playlist_downloader#2]
I just ran the command in the terminal:-

``` bash 
pip install Playlist
```
![image](https://github.com/user-attachments/assets/18804280-f65b-4e72-94d2-19c7c26f9ce5)

And it returned with no package found. Kindly release the package as cloning and downloading the repo seems a bit problematic every time.

**Comment by deepanshu414** [comment]
@yashksaini-coder

We will upload the package as soon as feasible. The upload has been delayed due to unforeseen circumstances. We appreciate your patience and understanding.

Thank you for your cooperation in this matter.

Best regards,
@deepanshu414

**Comment by yashksaini-coder** [comment]
If I can be of some assistance do let me know. @deepanshu414

**Comment by deepanshu414** [comment]
Thank you for your offer, @yashksaini-coder. I appreciate your assistance, but I can manage this package independently.

**Comment by deepanshu414** [comment]
@yashksaini-coder: I'm pleased to inform you that the package has been successfully uploaded. You can now find the 'Playlist_downloader' package on PyPI. Please review and let me know if you need any further information or assistance.

**Comment by yashksaini-coder** [comment]
I verified the packages and it is perfectly fine.

![image](https://github.com/user-attachments/assets/98eaed2c-e9ba-43a4-8763-2f31dc137e84)
